spring:
  application:
    name: management-composite-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true

user:
  role: hello shawn
