
server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://huskyproject.cmxa7p2e3tnw.us-east-2.rds.amazonaws.com
    username: admin
    password: Zz010013

  data:
    mongodb:
      uri: mongodb+srv://admin:Zz010013@huskyproject.ktn9x.mongodb.net/timesheet?retryWrites=true&w=majority

