
server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: employee-core-service
  data:
    mongodb:
      uri: mongodb+srv://admin:Zz010013@huskyproject.ktn9x.mongodb.net/timesheet?retryWrites=true&w=majority

server:
  port: 0
